import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/lib/context/auth-context";
import { Toaster } from "react-hot-toast";
import { ReactQueryContext } from "@/lib/context/react-query-context";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Bubur Nusantara App",
  description: "Generated by Bubur Nusantara app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryContext>
          <AuthContextProvider>
            {children}
            <Toaster position="bottom-right" />
          </AuthContextProvider>
        </ReactQueryContext>
      </body>
    </html>
  );
}
