import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/helper/context/userContext";
import { Toaster } from "react-hot-toast";
import ReactQueryContext from "@/helper/context/reactQueryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Bubur Nusantara App",
  description: "Generated by Bubur Nusantara app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryContext>
          <UserProvider>
            {children}
            <Toaster />
          </UserProvider>
        </ReactQueryContext>
      </body>
    </html>
  );
}
